services:
  - type: web
    name: pastrycloud
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
